### ISSUE TITLE
access to OTG Snpcaller

### ISSUE THREAD

**Issue by tmelia** [rkleyner/PGM-WES-Pipeline#1]
Hi rkleyner,

I would like to test out your approach to analyze my own PGM data. However, I am having trouble getting responses from the OTG-snpcaller authors to get access to their software. I was wondering if you could upload/send me your copy of OTG-snpcaller. I do understand that you do not maintain the OTG-snpcaller.

Thanks

**Comment by rkleyner** [comment]
Hi tmelia,

Absolutely-the OTG-SNP caller files (as received from the authors) have been uploaded to the main repository, and the files used in the re-written program are in the Variant_Calling directory. 

Cheers, 
Robert
